// Archivo generado automáticamente desde deportes.xlsx.
// No edites este archivo a mano: ejecuta actualizar_deportes.py.

const DEPORTES = [
  {
    "id": 1,
    "codigo": "atletismo",
    "nombre": "Atletismo",
    "grupo": "fijo",
    "tamanoSimulacion": 40,
    "variabilidad": 3,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "atletismo"
  },
  {
    "id": 2,
    "codigo": "natacion",
    "nombre": "Natación",
    "grupo": "fijo",
    "tamanoSimulacion": 30,
    "variabilidad": 2,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "acuatico"
  },
  {
    "id": 3,
    "codigo": "gimnasia",
    "nombre": "Gimnasia",
    "grupo": "fijo_alternativo",
    "tamanoSimulacion": 18,
    "variabilidad": 3,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "gimnasia"
  },
  {
    "id": 4,
    "codigo": "remo",
    "nombre": "Remo",
    "grupo": "grande",
    "tamanoSimulacion": 14,
    "variabilidad": 2,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "acuatico"
  },
  {
    "id": 5,
    "codigo": "boxeo",
    "nombre": "Boxeo",
    "grupo": "grande",
    "tamanoSimulacion": 14,
    "variabilidad": 4,
    "pesoAparicion": 200,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "combate"
  },
  {
    "id": 6,
    "codigo": "piraguismo",
    "nombre": "Piragüismo",
    "grupo": "grande",
    "tamanoSimulacion": 14,
    "variabilidad": 2,
    "pesoAparicion": 200,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "acuatico"
  },
  {
    "id": 7,
    "codigo": "ciclismo",
    "nombre": "Ciclismo",
    "grupo": "fijo_alternativo",
    "tamanoSimulacion": 18,
    "variabilidad": 3,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "resistencia"
  },
  {
    "id": 8,
    "codigo": "judo",
    "nombre": "Judo",
    "grupo": "grande",
    "tamanoSimulacion": 14,
    "variabilidad": 4,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "combate"
  },
  {
    "id": 9,
    "codigo": "tiro",
    "nombre": "Tiro",
    "grupo": "grande",
    "tamanoSimulacion": 14,
    "variabilidad": 5,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "precision"
  },
  {
    "id": 10,
    "codigo": "futbol",
    "nombre": "Fútbol",
    "grupo": "pequeno",
    "tamanoSimulacion": 2,
    "variabilidad": 4,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "equipo"
  },
  {
    "id": 11,
    "codigo": "baloncesto",
    "nombre": "Baloncesto",
    "grupo": "pequeno",
    "tamanoSimulacion": 2,
    "variabilidad": 2,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "equipo"
  },
  {
    "id": 12,
    "codigo": "waterpolo",
    "nombre": "Waterpolo",
    "grupo": "pequeno",
    "tamanoSimulacion": 2,
    "variabilidad": 3,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "equipo"
  },
  {
    "id": 13,
    "codigo": "balonmano",
    "nombre": "Balonmano",
    "grupo": "pequeno",
    "tamanoSimulacion": 2,
    "variabilidad": 3,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "equipo"
  },
  {
    "id": 14,
    "codigo": "voleibol",
    "nombre": "Voleibol",
    "grupo": "pequeno",
    "tamanoSimulacion": 2,
    "variabilidad": 3,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "equipo"
  },
  {
    "id": 15,
    "codigo": "tenis",
    "nombre": "Tenis",
    "grupo": "mediano",
    "tamanoSimulacion": 5,
    "variabilidad": 3,
    "pesoAparicion": 200,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "raqueta"
  },
  {
    "id": 16,
    "codigo": "escalada",
    "nombre": "Escalada",
    "grupo": "mediano",
    "tamanoSimulacion": 5,
    "variabilidad": 4,
    "pesoAparicion": 200,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 4,
    "categoria": "aventura"
  },
  {
    "id": 17,
    "codigo": "tenismesa",
    "nombre": "Tenis de mesa",
    "grupo": "mediano",
    "tamanoSimulacion": 5,
    "variabilidad": 1,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "raqueta"
  },
  {
    "id": 18,
    "codigo": "badminton",
    "nombre": "Bádminton",
    "grupo": "mediano",
    "tamanoSimulacion": 5,
    "variabilidad": 2,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "raqueta"
  },
  {
    "id": 19,
    "codigo": "rugby",
    "nombre": "Rugby 7",
    "grupo": "pequeno",
    "tamanoSimulacion": 2,
    "variabilidad": 4,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 4,
    "categoria": "equipo"
  },
  {
    "id": 20,
    "codigo": "tiroarco",
    "nombre": "Tiro con arco",
    "grupo": "mediano",
    "tamanoSimulacion": 5,
    "variabilidad": 2,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "precision"
  },
  {
    "id": 21,
    "codigo": "hockey",
    "nombre": "Hockey hierba",
    "grupo": "pequeno",
    "tamanoSimulacion": 2,
    "variabilidad": 3,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "equipo"
  },
  {
    "id": 22,
    "codigo": "esgrima",
    "nombre": "Esgrima",
    "grupo": "grande",
    "tamanoSimulacion": 14,
    "variabilidad": 4,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "combate"
  },
  {
    "id": 23,
    "codigo": "saltos",
    "nombre": "Saltos",
    "grupo": "mediano",
    "tamanoSimulacion": 5,
    "variabilidad": 2,
    "pesoAparicion": 100,
    "permiteEventos": true,
    "activo": true,
    "icono": null,
    "medallasPorPrueba": 3,
    "categoria": "acuatico"
  }
];
