// Archivo generado automáticamente desde paises.xlsx.
// No edites este archivo a mano: ejecuta actualizar_paises.py.
// Las notas se consultan con pais.notas[deporte.codigo].

const PAISES = [
  {
    "id": 1,
    "codigo": "ESP",
    "nombre": "España",
    "continente": "Europa",
    "activo": true,
    "notas": {
      "atletismo": 5,
      "natacion": 3,
      "gimnasia": 5,
      "remo": 5,
      "boxeo": 6,
      "piraguismo": 9,
      "ciclismo": 5,
      "judo": 7,
      "tiro": 6,
      "futbol": 9,
      "baloncesto": 8,
      "waterpolo": 9,
      "balonmano": 8,
      "voleibol": 3,
      "tenis": 9,
      "escalada": 6,
      "tenismesa": 2,
      "badminton": 4,
      "rugby": 5,
      "tiroarco": 5,
      "hockey": 6,
      "esgrima": 5,
      "saltos": 3
    }
  },
  {
    "id": 2,
    "codigo": "USA",
    "nombre": "Estados Unidos",
    "continente": "América",
    "activo": true,
    "notas": {
      "atletismo": 9,
      "natacion": 9,
      "gimnasia": 8,
      "remo": 7,
      "boxeo": 8,
      "piraguismo": 5,
      "ciclismo": 7,
      "judo": 3,
      "tiro": 8,
      "futbol": 7,
      "baloncesto": 10,
      "waterpolo": 8,
      "balonmano": 1,
      "voleibol": 9,
      "tenis": 8,
      "escalada": 7,
      "tenismesa": 1,
      "badminton": 1,
      "rugby": 7,
      "tiroarco": 7,
      "hockey": 3,
      "esgrima": 8,
      "saltos": 7
    }
  },
  {
    "id": 3,
    "codigo": "ITA",
    "nombre": "Italia",
    "continente": "Europa",
    "activo": true,
    "notas": {
      "atletismo": 6,
      "natacion": 7,
      "gimnasia": 8,
      "remo": 7,
      "boxeo": 5,
      "piraguismo": 7,
      "ciclismo": 8,
      "judo": 7,
      "tiro": 9,
      "futbol": 5,
      "baloncesto": 5,
      "waterpolo": 8,
      "balonmano": 2,
      "voleibol": 8,
      "tenis": 7,
      "escalada": 5,
      "tenismesa": 1,
      "badminton": 0,
      "rugby": 1,
      "tiroarco": 6,
      "hockey": 2,
      "esgrima": 9,
      "saltos": 6
    }
  },
  {
    "id": 4,
    "codigo": "FRA",
    "nombre": "Francia",
    "continente": "Europa",
    "activo": true,
    "notas": {
      "atletismo": 6,
      "natacion": 7,
      "gimnasia": 5,
      "remo": 6,
      "boxeo": 7,
      "piraguismo": 7,
      "ciclismo": 8,
      "judo": 9,
      "tiro": 7,
      "futbol": 8,
      "baloncesto": 9,
      "waterpolo": 4,
      "balonmano": 9,
      "voleibol": 8,
      "tenis": 7,
      "escalada": 7,
      "tenismesa": 4,
      "badminton": 1,
      "rugby": 8,
      "tiroarco": 7,
      "hockey": 3,
      "esgrima": 9,
      "saltos": 3
    }
  },
  {
    "id": 5,
    "codigo": "CHN",
    "nombre": "China",
    "continente": "Asia",
    "activo": true,
    "notas": {
      "atletismo": 5,
      "natacion": 8,
      "gimnasia": 9,
      "remo": 7,
      "boxeo": 8,
      "piraguismo": 8,
      "ciclismo": 6,
      "judo": 7,
      "tiro": 10,
      "futbol": 0,
      "baloncesto": 2,
      "waterpolo": 2,
      "balonmano": 0,
      "voleibol": 7,
      "tenis": 6,
      "escalada": 7,
      "tenismesa": 10,
      "badminton": 9,
      "rugby": 4,
      "tiroarco": 7,
      "hockey": 5,
      "esgrima": 6,
      "saltos": 10
    }
  },
  {
    "id": 6,
    "codigo": "JAM",
    "nombre": "Jamaica",
    "continente": "América",
    "activo": true,
    "notas": {
      "atletismo": 7,
      "natacion": 1,
      "gimnasia": 0,
      "remo": 0,
      "boxeo": 1,
      "piraguismo": 0,
      "ciclismo": 1,
      "judo": 0,
      "tiro": 0,
      "futbol": 1,
      "baloncesto": 0,
      "waterpolo": 0,
      "balonmano": 0,
      "voleibol": 0,
      "tenis": 1,
      "escalada": 0,
      "tenismesa": 0,
      "badminton": 0,
      "rugby": 0,
      "tiroarco": 0,
      "hockey": 1,
      "esgrima": 0,
      "saltos": 0
    }
  },
  {
    "id": 7,
    "codigo": "KEN",
    "nombre": "Kenia",
    "continente": "África",
    "activo": true,
    "notas": {
      "atletismo": 7,
      "natacion": 0,
      "gimnasia": 0,
      "remo": 0,
      "boxeo": 3,
      "piraguismo": 0,
      "ciclismo": 0,
      "judo": 0,
      "tiro": 0,
      "futbol": 0,
      "baloncesto": 0,
      "waterpolo": 0,
      "balonmano": 0,
      "voleibol": 2,
      "tenis": 0,
      "escalada": 0,
      "tenismesa": 0,
      "badminton": 0,
      "rugby": 5,
      "tiroarco": 0,
      "hockey": 1,
      "esgrima": 1,
      "saltos": 0
    }
  },
  {
    "id": 8,
    "codigo": "CUB",
    "nombre": "Cuba",
    "continente": "América",
    "activo": true,
    "notas": {
      "atletismo": 4,
      "natacion": 1,
      "gimnasia": 2,
      "remo": 3,
      "boxeo": 9,
      "piraguismo": 5,
      "ciclismo": 1,
      "judo": 6,
      "tiro": 4,
      "futbol": 1,
      "baloncesto": 0,
      "waterpolo": 0,
      "balonmano": 0,
      "voleibol": 4,
      "tenis": 0,
      "escalada": 0,
      "tenismesa": 1,
      "badminton": 0,
      "rugby": 1,
      "tiroarco": 2,
      "hockey": 1,
      "esgrima": 3,
      "saltos": 3
    }
  },
  {
    "id": 9,
    "codigo": "GER",
    "nombre": "Alemania",
    "continente": "Europa",
    "activo": true,
    "notas": {
      "atletismo": 5,
      "natacion": 5,
      "gimnasia": 6,
      "remo": 8,
      "boxeo": 6,
      "piraguismo": 9,
      "ciclismo": 7,
      "judo": 7,
      "tiro": 6,
      "futbol": 8,
      "baloncesto": 7,
      "waterpolo": 2,
      "balonmano": 8,
      "voleibol": 4,
      "tenis": 6,
      "escalada": 4,
      "tenismesa": 4,
      "badminton": 2,
      "rugby": 1,
      "tiroarco": 6,
      "hockey": 9,
      "esgrima": 5,
      "saltos": 5
    }
  },
  {
    "id": 10,
    "codigo": "JPN",
    "nombre": "Japón",
    "continente": "Asia",
    "activo": true,
    "notas": {
      "atletismo": 2,
      "natacion": 6,
      "gimnasia": 8,
      "remo": 2,
      "boxeo": 5,
      "piraguismo": 3,
      "ciclismo": 3,
      "judo": 10,
      "tiro": 3,
      "futbol": 5,
      "baloncesto": 5,
      "waterpolo": 2,
      "balonmano": 2,
      "voleibol": 6,
      "tenis": 5,
      "escalada": 9,
      "tenismesa": 8,
      "badminton": 7,
      "rugby": 3,
      "tiroarco": 6,
      "hockey": 3,
      "esgrima": 8,
      "saltos": 5
    }
  },
  {
    "id": 11,
    "codigo": "GBR",
    "nombre": "Reino Unido",
    "continente": "Europa",
    "activo": true,
    "notas": {
      "atletismo": 7,
      "natacion": 7,
      "gimnasia": 8,
      "remo": 9,
      "boxeo": 8,
      "piraguismo": 8,
      "ciclismo": 9,
      "judo": 4,
      "tiro": 7,
      "futbol": 8,
      "baloncesto": 2,
      "waterpolo": 1,
      "balonmano": 1,
      "voleibol": 1,
      "tenis": 5,
      "escalada": 7,
      "tenismesa": 2,
      "badminton": 4,
      "rugby": 8,
      "tiroarco": 5,
      "hockey": 7,
      "esgrima": 3,
      "saltos": 8
    }
  },
  {
    "id": 12,
    "codigo": "KOR",
    "nombre": "Corea del Sur",
    "continente": "Asia",
    "activo": true,
    "notas": {
      "atletismo": 1,
      "natacion": 4,
      "gimnasia": 5,
      "remo": 1,
      "boxeo": 4,
      "piraguismo": 2,
      "ciclismo": 1,
      "judo": 8,
      "tiro": 8,
      "futbol": 4,
      "baloncesto": 2,
      "waterpolo": 0,
      "balonmano": 4,
      "voleibol": 5,
      "tenis": 1,
      "escalada": 6,
      "tenismesa": 6,
      "badminton": 8,
      "rugby": 1,
      "tiroarco": 10,
      "hockey": 4,
      "esgrima": 7,
      "saltos": 2
    }
  },
  {
    "id": 13,
    "codigo": "ETH",
    "nombre": "Etiopía",
    "continente": "África",
    "activo": true,
    "notas": {
      "atletismo": 6,
      "natacion": 1,
      "gimnasia": 0,
      "remo": 0,
      "boxeo": 0,
      "piraguismo": 0,
      "ciclismo": 1,
      "judo": 0,
      "tiro": 0,
      "futbol": 0,
      "baloncesto": 0,
      "waterpolo": 0,
      "balonmano": 0,
      "voleibol": 0,
      "tenis": 0,
      "escalada": 0,
      "tenismesa": 0,
      "badminton": 0,
      "rugby": 1,
      "tiroarco": 0,
      "hockey": 0,
      "esgrima": 0,
      "saltos": 0
    }
  },
  {
    "id": 14,
    "codigo": "AUS",
    "nombre": "Australia",
    "continente": "Oceanía",
    "activo": true,
    "notas": {
      "atletismo": 5,
      "natacion": 9,
      "gimnasia": 3,
      "remo": 7,
      "boxeo": 5,
      "piraguismo": 7,
      "ciclismo": 8,
      "judo": 2,
      "tiro": 4,
      "futbol": 4,
      "baloncesto": 8,
      "waterpolo": 7,
      "balonmano": 1,
      "voleibol": 1,
      "tenis": 6,
      "escalada": 2,
      "tenismesa": 1,
      "badminton": 1,
      "rugby": 9,
      "tiroarco": 3,
      "hockey": 8,
      "esgrima": 1,
      "saltos": 7
    }
  },
  {
    "id": 15,
    "codigo": "IND",
    "nombre": "India",
    "continente": "Asia",
    "activo": true,
    "notas": {
      "atletismo": 2,
      "natacion": 1,
      "gimnasia": 1,
      "remo": 1,
      "boxeo": 4,
      "piraguismo": 0,
      "ciclismo": 0,
      "judo": 1,
      "tiro": 6,
      "futbol": 0,
      "baloncesto": 0,
      "waterpolo": 0,
      "balonmano": 0,
      "voleibol": 0,
      "tenis": 4,
      "escalada": 0,
      "tenismesa": 4,
      "badminton": 6,
      "rugby": 0,
      "tiroarco": 6,
      "hockey": 7,
      "esgrima": 2,
      "saltos": 1
    }
  },
  {
    "id": 16,
    "codigo": "HUN",
    "nombre": "Hungría",
    "continente": "Europa",
    "activo": true,
    "notas": {
      "atletismo": 2,
      "natacion": 6,
      "gimnasia": 2,
      "remo": 1,
      "boxeo": 2,
      "piraguismo": 8,
      "ciclismo": 3,
      "judo": 3,
      "tiro": 4,
      "futbol": 1,
      "baloncesto": 0,
      "waterpolo": 8,
      "balonmano": 6,
      "voleibol": 0,
      "tenis": 2,
      "escalada": 1,
      "tenismesa": 2,
      "badminton": 1,
      "rugby": 0,
      "tiroarco": 1,
      "hockey": 0,
      "esgrima": 8,
      "saltos": 1
    }
  },
  {
    "id": 17,
    "codigo": "NED",
    "nombre": "Países Bajos",
    "continente": "Europa",
    "activo": true,
    "notas": {
      "atletismo": 6,
      "natacion": 5,
      "gimnasia": 4,
      "remo": 9,
      "boxeo": 4,
      "piraguismo": 2,
      "ciclismo": 9,
      "judo": 6,
      "tiro": 0,
      "futbol": 5,
      "baloncesto": 1,
      "waterpolo": 7,
      "balonmano": 6,
      "voleibol": 4,
      "tenis": 3,
      "escalada": 1,
      "tenismesa": 1,
      "badminton": 1,
      "rugby": 2,
      "tiroarco": 6,
      "hockey": 10,
      "esgrima": 3,
      "saltos": 3
    }
  },
  {
    "id": 18,
    "codigo": "SMR",
    "nombre": "San Marino",
    "continente": "Europa",
    "activo": true,
    "notas": {
      "atletismo": 0,
      "natacion": 0,
      "gimnasia": 0,
      "remo": 0,
      "boxeo": 0,
      "piraguismo": 0,
      "ciclismo": 0,
      "judo": 0,
      "tiro": 4,
      "futbol": 0,
      "baloncesto": 0,
      "waterpolo": 0,
      "balonmano": 0,
      "voleibol": 0,
      "tenis": 0,
      "escalada": 0,
      "tenismesa": 0,
      "badminton": 0,
      "rugby": 0,
      "tiroarco": 0,
      "hockey": 0,
      "esgrima": 1,
      "saltos": 0
    }
  },
  {
    "id": 19,
    "codigo": "MEX",
    "nombre": "México",
    "continente": "América",
    "activo": true,
    "notas": {
      "atletismo": 2,
      "natacion": 1,
      "gimnasia": 2,
      "remo": 2,
      "boxeo": 5,
      "piraguismo": 1,
      "ciclismo": 3,
      "judo": 3,
      "tiro": 4,
      "futbol": 5,
      "baloncesto": 1,
      "waterpolo": 0,
      "balonmano": 0,
      "voleibol": 2,
      "tenis": 2,
      "escalada": 1,
      "tenismesa": 1,
      "badminton": 1,
      "rugby": 1,
      "tiroarco": 7,
      "hockey": 1,
      "esgrima": 2,
      "saltos": 8
    }
  },
  {
    "id": 20,
    "codigo": "BRA",
    "nombre": "Brasil",
    "continente": "América",
    "activo": true,
    "notas": {
      "atletismo": 3,
      "natacion": 4,
      "gimnasia": 7,
      "remo": 1,
      "boxeo": 6,
      "piraguismo": 6,
      "ciclismo": 2,
      "judo": 8,
      "tiro": 2,
      "futbol": 9,
      "baloncesto": 4,
      "waterpolo": 2,
      "balonmano": 6,
      "voleibol": 9,
      "tenis": 5,
      "escalada": 0,
      "tenismesa": 3,
      "badminton": 1,
      "rugby": 2,
      "tiroarco": 4,
      "hockey": 1,
      "esgrima": 4,
      "saltos": 2
    }
  },
  {
    "id": 21,
    "codigo": "ARG",
    "nombre": "Argentina",
    "continente": "América",
    "activo": true,
    "notas": {
      "atletismo": 1,
      "natacion": 2,
      "gimnasia": 1,
      "remo": 2,
      "boxeo": 4,
      "piraguismo": 3,
      "ciclismo": 3,
      "judo": 5,
      "tiro": 3,
      "futbol": 7,
      "baloncesto": 5,
      "waterpolo": 1,
      "balonmano": 3,
      "voleibol": 6,
      "tenis": 6,
      "escalada": 1,
      "tenismesa": 1,
      "badminton": 0,
      "rugby": 7,
      "tiroarco": 2,
      "hockey": 8,
      "esgrima": 2,
      "saltos": 1
    }
  },
  {
    "id": 22,
    "codigo": "TPE",
    "nombre": "Taipei",
    "continente": "Asia",
    "activo": true,
    "notas": {
      "atletismo": 1,
      "natacion": 1,
      "gimnasia": 4,
      "remo": 1,
      "boxeo": 6,
      "piraguismo": 1,
      "ciclismo": 1,
      "judo": 4,
      "tiro": 4,
      "futbol": 0,
      "baloncesto": 0,
      "waterpolo": 0,
      "balonmano": 0,
      "voleibol": 0,
      "tenis": 3,
      "escalada": 1,
      "tenismesa": 6,
      "badminton": 8,
      "rugby": 0,
      "tiroarco": 7,
      "hockey": 1,
      "esgrima": 2,
      "saltos": 1
    }
  },
  {
    "id": 23,
    "codigo": "AUT",
    "nombre": "Austria",
    "continente": "Europa",
    "activo": true,
    "notas": {
      "atletismo": 2,
      "natacion": 3,
      "gimnasia": 2,
      "remo": 3,
      "boxeo": 1,
      "piraguismo": 4,
      "ciclismo": 4,
      "judo": 6,
      "tiro": 3,
      "futbol": 3,
      "baloncesto": 0,
      "waterpolo": 0,
      "balonmano": 3,
      "voleibol": 1,
      "tenis": 3,
      "escalada": 9,
      "tenismesa": 3,
      "badminton": 2,
      "rugby": 0,
      "tiroarco": 1,
      "hockey": 2,
      "esgrima": 3,
      "saltos": 2
    }
  },
  {
    "id": 24,
    "codigo": "FIJ",
    "nombre": "Fiji",
    "continente": "Oceanía",
    "activo": true,
    "notas": {
      "atletismo": 1,
      "natacion": 0,
      "gimnasia": 0,
      "remo": 0,
      "boxeo": 0,
      "piraguismo": 0,
      "ciclismo": 0,
      "judo": 0,
      "tiro": 0,
      "futbol": 0,
      "baloncesto": 0,
      "waterpolo": 0,
      "balonmano": 0,
      "voleibol": 0,
      "tenis": 0,
      "escalada": 0,
      "tenismesa": 0,
      "badminton": 0,
      "rugby": 10,
      "tiroarco": 0,
      "hockey": 0,
      "esgrima": 0,
      "saltos": 0
    }
  },
  {
    "id": 25,
    "codigo": "NZL",
    "nombre": "Nueva Zelanda",
    "continente": "Oceanía",
    "activo": true,
    "notas": {
      "atletismo": 4,
      "natacion": 4,
      "gimnasia": 2,
      "remo": 9,
      "boxeo": 3,
      "piraguismo": 8,
      "ciclismo": 6,
      "judo": 1,
      "tiro": 3,
      "futbol": 4,
      "baloncesto": 1,
      "waterpolo": 1,
      "balonmano": 0,
      "voleibol": 0,
      "tenis": 1,
      "escalada": 0,
      "tenismesa": 0,
      "badminton": 0,
      "rugby": 10,
      "tiroarco": 0,
      "hockey": 5,
      "esgrima": 1,
      "saltos": 3
    }
  },
  {
    "id": 26,
    "codigo": "BUL",
    "nombre": "Bulgaria",
    "continente": "Europa",
    "activo": true,
    "notas": {
      "atletismo": 2,
      "natacion": 1,
      "gimnasia": 7,
      "remo": 3,
      "boxeo": 5,
      "piraguismo": 2,
      "ciclismo": 1,
      "judo": 3,
      "tiro": 5,
      "futbol": 1,
      "baloncesto": 2,
      "waterpolo": 0,
      "balonmano": 1,
      "voleibol": 6,
      "tenis": 3,
      "escalada": 0,
      "tenismesa": 1,
      "badminton": 2,
      "rugby": 0,
      "tiroarco": 0,
      "hockey": 0,
      "esgrima": 2,
      "saltos": 1
    }
  },
  {
    "id": 27,
    "codigo": "CAN",
    "nombre": "Canadá",
    "continente": "América",
    "activo": true,
    "notas": {
      "atletismo": 7,
      "natacion": 8,
      "gimnasia": 5,
      "remo": 7,
      "boxeo": 4,
      "piraguismo": 6,
      "ciclismo": 5,
      "judo": 7,
      "tiro": 2,
      "futbol": 6,
      "baloncesto": 6,
      "waterpolo": 4,
      "balonmano": 0,
      "voleibol": 4,
      "tenis": 6,
      "escalada": 2,
      "tenismesa": 2,
      "badminton": 1,
      "rugby": 8,
      "tiroarco": 3,
      "hockey": 2,
      "esgrima": 5,
      "saltos": 6
    }
  },
  {
    "id": 28,
    "codigo": "ROU",
    "nombre": "Rumanía",
    "continente": "Europa",
    "activo": true,
    "notas": {
      "atletismo": 2,
      "natacion": 4,
      "gimnasia": 6,
      "remo": 9,
      "boxeo": 1,
      "piraguismo": 3,
      "ciclismo": 2,
      "judo": 4,
      "tiro": 2,
      "futbol": 2,
      "baloncesto": 0,
      "waterpolo": 3,
      "balonmano": 4,
      "voleibol": 2,
      "tenis": 4,
      "escalada": 0,
      "tenismesa": 3,
      "badminton": 0,
      "rugby": 1,
      "tiroarco": 2,
      "hockey": 0,
      "esgrima": 6,
      "saltos": 2
    }
  },
  {
    "id": 29,
    "codigo": "RSA",
    "nombre": "Sudáfrica",
    "continente": "África",
    "activo": true,
    "notas": {
      "atletismo": 4,
      "natacion": 5,
      "gimnasia": 1,
      "remo": 5,
      "boxeo": 1,
      "piraguismo": 2,
      "ciclismo": 5,
      "judo": 1,
      "tiro": 1,
      "futbol": 1,
      "baloncesto": 0,
      "waterpolo": 1,
      "balonmano": 0,
      "voleibol": 0,
      "tenis": 2,
      "escalada": 2,
      "tenismesa": 0,
      "badminton": 1,
      "rugby": 8,
      "tiroarco": 1,
      "hockey": 3,
      "esgrima": 1,
      "saltos": 2
    }
  },
  {
    "id": 30,
    "codigo": "CZE",
    "nombre": "República Checa",
    "continente": "Europa",
    "activo": true,
    "notas": {
      "atletismo": 4,
      "natacion": 2,
      "gimnasia": 1,
      "remo": 4,
      "boxeo": 1,
      "piraguismo": 8,
      "ciclismo": 4,
      "judo": 5,
      "tiro": 6,
      "futbol": 2,
      "baloncesto": 4,
      "waterpolo": 1,
      "balonmano": 2,
      "voleibol": 5,
      "tenis": 9,
      "escalada": 7,
      "tenismesa": 2,
      "badminton": 2,
      "rugby": 1,
      "tiroarco": 1,
      "hockey": 1,
      "esgrima": 5,
      "saltos": 1
    }
  }
];
